### ISSUE TITLE
Missing parts in BOM?

### ISSUE THREAD

**Issue by hurda** [amoore2600/GBS-C_AIO#1]
Hello!

The readme says that the BOM may be missing some parts.
Could you tell me please, what parts are missing, if any?

Thank you very much.

**Comment by damopinn** [comment]
Hi, have a look at the images you can see the built project. I can see a 2pin  cable that connects the power.  There are also parts not installed like the 15pin headers and the micro usb connector. I think the usb socket is for powering the hdmi converter, so you could leave that out if you dont want that. The screw connector are swapped for jst connectors too, so you could change them if you wanted to.
