### ISSUE TITLE
The project website is down.

### ISSUE THREAD

**Issue by InvisibleFunction** [amoore2600/GBS-C_AIO#4]
Going to gbscaio.com leads to a Wix error page.

**Comment by cglmrfreeman** [comment]
This was discussed in the Facebook group sometime ago. The website and form cost money to maintain. @amoore2600 is no longer interested in fronting the costs for this as it's not necessary.

**Comment by InvisibleFunction** [comment]
Why don't you change the link to point to the facebook group then?

**Comment by cglmrfreeman** [comment]
The link for the Facebook group is in the main README.md. There is no reason to maintain the domain as I assume it will expire eventually anyway as there is no point to renewing the domain when there is no website to host.

**Comment by InvisibleFunction** [comment]
That's fine, I'm just saying that when people come to the repo and follow the link on the main page under the about section it leads to a dead website.

![Screen Shot 2021-11-18 at 22 00 56](https://user-images.githubusercontent.com/3682184/142557804-03ef705b-c17a-4038-a4b4-75d61a599856.png)

So maybe remove it? or change it to point to the facebook group if that's the new website.

**Comment by cglmrfreeman** [comment]
There is also a reference to the website in the README.md [listing the user forum](
https://github.com/amoore2600/GBS-C_AIO/blob/main/README.md?plain=1#L52), which was also taken down on October 31, 2021.

However, I fail to see your ultimate point here. In what way does having or not having a website affect the project as a whole? The project itself is still intact and perfectly capable from being built from start to finish with the information provided here. The site offered nothing more than a fancy portal for when the authors were producing and selling the project as preassembled kits, which they no longer do.

As far as the project is concerned, the fact that gbscaio.com no longer exists does not affect this project at all and is not really an issue. If you really are so nit-picky, however, I suppose you could fork and initiate a pull request to remove the website from the README.md (and possibly fix the spelling of [GBScontorl](https://github.com/amoore2600/GBS-C_AIO/blob/main/README.md?plain=1#L46)) or replace it with an [archive.org version](https://web.archive.org/web/20211027223730/https://www.gbscaio.com/) but the fact that this issue has remained up for nearly 20 days without the project owner commenting or closing this issue means you probably won't get very far with that.

**Comment by InvisibleFunction** [comment]
I made a PR: https://github.com/amoore2600/GBS-C_AIO/pull/6

I agree that it doesn't matter if you have a website or just use a facebook group, but linking to a dead website over a functioning facebook page doesn't seem like it has a benefit.

**Comment by omfgtora** [comment]
Linking to a dead domain and not wanting to change it or remove it is pretty ridiculous.

**Comment by biggestsonicfan** [comment]
> Linking to a dead domain and not wanting to change it or remove it is pretty ridiculous.

But they did? PR 6 was approved and merged? Where are you seeing the old domain?

**Comment by InvisibleFunction** [comment]
> But they did? PR 6 was approved and merged? Where are you seeing the old domain?

Go here: https://github.com/amoore2600/GBS-C_AIO

Under the About section in the upper right (also see my screenshot in my third post of this issue).

**Comment by biggestsonicfan** [comment]
I thought that would have been taken care of with the PR 6 merge, and it appears @amoore2600 is inactive on git (at least with public repos)

**Comment by omfgtora** [comment]
https://gbscaio.com/ is still linked on the GitHub info of the repo.
