### ISSUE TITLE
Link to dead website in description

### ISSUE THREAD

**Issue by erobertsme** [amoore2600/GBS-C_AIO#8]
Issue #4 was closed for some reason, yet the dead website is still linked in the description of the repo. Please remove this dead URL.

Here is a screenshot with the link highlighted to make sure this request is understood, since the previous issue was closed without resolving the actual issue.
![image](https://github.com/amoore2600/GBS-C_AIO/assets/9193319/0c2ff863-94e1-4576-8729-0976884aa6e4)

**Comment by biggestsonicfan** [comment]
I really really really really don't think they care and the repo should probably just be archived by the owner a this point lol

**Comment by erobertsme** [comment]
> I really really really really don't think they care and the repo should probably just be archived by the owner a this point lol

Then this open issue should serve as a warning.

**Comment by amoore2600** [comment]
https://www.facebook.com/groups/gbscaio

**Comment by erobertsme** [comment]
Description update. Thank you @amoore2600
